version: '3.6'

services:
  db_postgres:
    image: 'docker.io/postgres:14-alpine'
    volumes:
      - '../volumes/aliato/db_postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=localhost
    ports:
      - '5432:5432'
    networks:
      - aliato-network
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "16543:80"
    depends_on:
      - db_postgres
    networks:
      - aliato-network

networks:
  aliato-network:
    driver: bridge
