# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  username: postgres
  password: postgres
  port: <%= ENV.fetch('DB_PORT', '5432') %>

development:
  <<: *default
  database: aliato_development

test:
  <<: *default
  database: aliato_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || 5 %>
  sslmode: require
