# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV.fetch('DB_HOST', 'postgres') %>
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'postgres') %>
  port: <%= ENV.fetch('DB_PORT', '5432') %>

development:
  primary: &primary_production
    <<: *default
    database: aliato_development
  cable:
    adapter: sqlite3
    pool: <%= ENV.fetch("RAILS_MAX_THREADS_CABLE") { 5 } %>
    timeout: 5000
    database: storage/development_cable.sqlite3
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: aliato_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV["DB_POOL"] || 5 %>
    sslmode: require
    statement_limit: 200
  cable:
    adapter: sqlite3
    pool: <%= ENV.fetch("RAILS_MAX_THREADS_CABLE") { 5 } %>
    timeout: 5000
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
